# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 677385eb92ea68ffdf290df9fd6079b8a7578b5d7b71a2f7602988cb335b3d60708d635014b197113a5936af0c0d3c222ecb19b21c008fec0a50b63ab4d9d9ad

test:
  secret_key_base: e079722ad4c67ed69f9ec1d64c1a38aff391b9f10a23832c489384e30c72d5439abdc9bfbba9692e3c8908fbf84401e8e69df046eb8a1d6fae2a2f83b1d0ea3e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
